language: node_js
node_js: 
  - "stable"
before_script: 
  - cd api
  - npm install
  - chmod 0755 node_modules/.bin/_mocha
script:  
  - npm run test:travis
cache:
  directories:
    - "api/node_modules"