language: node_js
node_js: 
  - "node"
env:
  - NODE_ENV=test
  global: CODECLIMATE_REPO_TOKEN=eb1d19652a04b63c35488a0f191667d307108e7673792f96269145d7d29ea542
install:
  - cd api
  - npm install
services:
  - postgresql    
cache:
  directories:
    - "api/node_modules"
before_script:
    - psql -c 'create database bookmeal;' -U postgres
    # - psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
    # - npm run build
    - sequelize db:migrate
    # - sequelize db:seed:all
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
  # - npm test:travis
  - npm run coverage
after_success:
    - npm run coverage
    - npm install codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT  

